version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:80" # Místní port 8080 bude mapován na port 80 uvnitř kontejneru
    volumes:
      - ./data:/usr/share/nginx/html # Volitelně: udržuj obsah aplikace synchronizovaný
    restart: unless-stopped
