services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8081:80" # Místní port 8080 bude mapován na port 80 uvnitř kontejneru
    volumes:
      - web_data:/usr/share/nginx/html # Volitelně: udržuj obsah aplikace synchronizovaný
    restart: unless-stopped
